import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@components/Nav';
import Footer from '@components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* <div className='main'>
          <div className='gradient'>
          </div>
        </div> */}
        <main className='app h-screen'>
          <Nav></Nav>
          
          {children}
          <Footer></Footer>
        </main>
      </body>
    </html>
  )
}
